development:
  default:
    host: <%= ENV['FILEMAKER_HOST'] || 'slc.usaconservation.org' %>
    account_name: <%= ENV['FILEMAKER_ACCOUNT_NAME'] || 'Admin' %>
    password: <%= ENV['FILEMAKER_PASSWORD'] || 'admin' %>

production:
  default:
    host: <%= ENV['FILEMAKER_HOST'] || 'slc.usaconservation.org' %>
    account_name: <%= ENV['FILEMAKER_ACCOUNT_NAME'] || 'Matrix' %>
    password: <%= ENV['FILEMAKER_PASSWORD'] || 'G3k#zR&59mQ?4U' %>